apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-app-deployment
  labels:
    app: shark-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shark-app
  template:
    metadata:
      labels:
        app: shark-app
    spec:
      containers:
      - name: shark-app
        image: basha999/node-app:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: shark-app-service
spec:
  type: NodePort
  selector:
    app: shark-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
